spring.application.name=alifc-jbackend
server.port=15300
# Add any other local-specific properties here
#oss.endpoint=oss-cn-hongkong.aliyuncs.com
#oss.accessKeyID=LTAI5t92exgN59SrcJXqQViD
#oss.accessKeySecret=LSwHiGKNLkFgJUTjAAUZRoaSss1JCD
#oss.region=cn-hongkong
#oss.bucketName=leanhoss
#dir.path=csm_datas
